### ISSUE TITLE
Missing line break in the beginning of lines

### ISSUE THREAD

**Issue by tizee** [errorer/Portal_StillAlive_Python#1]
https://github.com/errorer/Portal_StillAlive_Python/blob/b3c2a4276abb5d8c99baa9250c15463a44708f9a/still_alive_credit.py#L648-L651

Running the script in the terminal larger than 80x24 would fail to render first few lines properly due to above lines of code.
It's okay to enable new lines here  as the cursor is controlled by the control characters and global variables which define the position of the cursor.

![recording](https://user-images.githubusercontent.com/33030965/134534921-66c48f10-9fcc-448e-8267-f5701e010299.gif)

**Comment by errorer** [comment]
Thank you for fixing the issue. Indeed my default terminals are all 80*24. I have no idea why I missed line return on these lines.
